### ISSUE TITLE
Error bars doesnt match with components

### ISSUE THREAD

**Issue by daliavirginia** [VSainteuf/mcssa#6]
I've been using this lib and found that the error bars may be missplaced when the plot is vs frequency. For example: 

![image](https://user-images.githubusercontent.com/87842499/166952366-4225cc32-87b5-4f4e-9196-243f67b1894d.png)

I applied mcssa to a precipitation series. When the plot is vs eigenvalue there are not significant components. When is vs frequencies, 4 components seems to be significants. Is the same SSA applied at the same series. Any idea?

**Comment by VSainteuf** [comment]
Hi @daliavirginia ,
Thanks for pointing this out, there seems to be a problem indeed. 
I think the issue is that in the plotting function [here](https://github.com/VSainteuf/mcssa/blob/af2a453df23f8fc57a7bd5e3cd2322465ebaab4e/mcssa/utils.py#L270) the error bars are not re-ordered by frequency even when `freq_rank` is True. So the error bars are actually plotted in eigenvalue rank at the position of the frequencies. That fits well with the Figure you provided. 
I'll prepare a branch with a patch and you can test it.

**Comment by VSainteuf** [comment]
Can you redo your figure using [this branch](https://github.com/VSainteuf/mcssa/tree/issue6) ?

**Comment by daliavirginia** [comment]
Thanks for answering, I tested the new branch and it works perfectly! The prove:

![image](https://user-images.githubusercontent.com/87842499/168327310-06b32304-a123-43d9-add8-fba6ef50d822.png)

These are the same plots I previously attached. Now both show the same significant components. 

Ty <3
